### ISSUE TITLE
Crash whenever right-clicking (with any item or empty hand) on projector

### ISSUE THREAD

**Issue by KMorris29** [Mysticpasta1/holographic-renders#6]
On an install with just Fabric 0.12.5, NotEnoughCrashes, and of course holo renders with the librarianlib & fabric language kotlin dependencies, I can run a world and place down a projector just fine. But whenever I right click on it, with an item from the mod, a vanilla item, or an empty hand, in any game mode except spectator, I get a crash to the title screen. Going back to the world works just fine, the projector is still there and I can place down more, but right click on any of them with anything? Crash.

NotEnoughCrashes gave me this link for one of the crashes, and it's the same for all the others: https://crashy.net/pO9Gq5sebeYUWyZY0I4G

**Comment by mrmelon54** [comment]
Its a class not found exception for "com.teamwizardry.librarianlib.facade.layers.text.TextFit" in ProjectorScreen.java line 40

Looks like the 1.18 version doesn't have the same issue as it doesn't use the library
